# Generated by Django 4.0.3 on 2022-03-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetroleumDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('petroleum_product', models.CharField(blank=True, max_length=100, null=True)),
                ('sale', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
